JessJiggs/soiree

- db/seeds.rb
- fix: minor bug on seed file from seeds branch
- chore: seed phone number fix to a string
> seed phone number fix to a string

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
Display Event on dashboard and route to event show page
> feat: able to show created event on index/dashboard

- Gemfile
- Gemfile.lock
- app/controllers/expenses_controller.rb
- app/javascript/application.js
- app/views/expenses/index.html.erb
- config/importmap.rb
- package.json
- yarn.lock
- initiated chart kick
- added pie chart
- modified pie chart to donut
- tying an expense to an event on the pie chart
> tying an expense to an event on the pie chart

- app/controllers/expenses_controller.rb
- app/views/events/show.html.erb
- app/views/expenses/index.html.erb
- added button to create expense from expense index
- added button to create expense from expense index
> added button to create expense from expense index

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_table.scss
- app/views/guests/index.html.erb
change these when styling 
class="btn btn-secondary"
class="btn btn-tertiary"
left text alignment
> <th class="text-table-std"> Name</th>
> <td class="text-table-std"><%= guest.first_name %></td>
centred text alignment 
> <th class="text-table-status"> Invitation Status</th>
> <td class="text-table-status"><strong><%= guest.invitation_status.humanize %></strong></td>
table has different border weighting and style - solid vs dotted.
> added table layout to guests

- app/views/guests/index.html.erb
- app/views/tasks/index.html.erb
> added a link back to event from task, added a placeholder for 'add task'

- app/controllers/events_controller.rb
- app/controllers/expenses_controller.rb
- app/views/events/show.html.erb
- package.json
- yarn.lock
... and then formatted the code
> Chore: formatted the date and time and addedd icons to it

- app/assets/stylesheets/components/_table.scss
- app/views/guests/index.html.erb
added div classes based on excalidraw. not yet complete - table headers need right convention naming wise.
> styling-guest-show

- app/controllers/pages_controller.rb
def home
if current_user
current_user.events ? @events = current_user.events : ""
else
render "pages/landing_page"
end
fixed now - we can view a user page with no event
> bugfix on home page no event

- app/assets/stylesheets/components/_table.scss
- app/views/pages/home.html.erb
fixed the if else statment on page home for create new event - image upload,
> Fix photo upload

- app/views/tasks/_task_infos.html.erb
added the icon for delete - to the tasks page (replaces "delete" link)
> added delete icon to tasks

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_input.scss
- app/views/events/show.html.erb
- app/views/expenses/index.html.erb
- app/views/guests/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Not done yet, but making smaller requests so that everyone can be up to date as the style changes take place
> updated page titles, containers, search input

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_input.scss
- app/views/pages/home.html.erb
> Style dashboard - events card and basic layout

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_chart.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_link.scss
- app/assets/stylesheets/components/_show_guests.scss
- app/assets/stylesheets/components/_table.scss
- app/controllers/guests_controller.rb
- app/views/guests/index.html.erb
fixed edit guest, 
added bar chart back 
added sub-navbar
started styling
> Style guests 2

- app/views/expenses/index.html.erb
adjusted page header and added sub nav bar
> Fix expense

- app/controllers/guests_controller.rb
- app/views/guests/index.html.erb
fiuxed the math on guests bar chart
> Graphs maths on bar chart

- app/views/expenses/index.html.erb
- app/views/guests/index.html.erb
fuixed the bug on edit without refresh by moving ivs and adding a th + td for hidden moodal
> fixed bug on edit without refresh -thanks scooter

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/components/_table.scss
- app/views/expenses/index.html.erb
- db/schema.rb
> added mb to container to add space on the bottom

- app/assets/stylesheets/components/_container.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> fixed note styling

- app/views/expenses/index.html.erb
worth it - fixed add guest "save" button
> fixed save on add expense

- app/views/pages/home.html.erb
fixed the order of event and task name on the dashbaord tasks list - my dashbaord.
> fix task name - task order on dashboard

- public/404.html
- public/422.html
complete hogwash but funny - lerts hope we dont get none of these . . .
> personalised the error messages

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/events/show.html.erb
- app/views/guests/index.html.erb
- app/views/pages/home.html.erb
fixed dashboard task colour and humanize, 
added scroll to guests table
looking guuuuuud
> fixed dashboard task colour and humanize, added scroll to guests table

- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_container.scss
- app/views/messages/index.html.erb
- fixed dashboard links spacing on chat page
- chatroom styling
> chatroom styling

- db/seeds.rb
> final seed fixed
